CLR_BG          = "#0D1F17"
CLR_SURFACE     = "#132B1E"
CLR_BORDER      = "#1F3D2B"
CLR_ACCENT      = "#D4F13A"
CLR_TEXT        = "#E8F5E9"
CLR_MUTED       = "#6B8F77"
CLR_HOME        = "#D4F13A"   # acid yellow  — home team
CLR_DRAW        = "#4A9B6F"   # mid green    — draw
CLR_AWAY        = "#1A6B42"   # deep green   — away team
CLR_SCORELINE   = "#2ECC71"   # bright green — scoreline bars